CREATE TYPE level AS ENUM('Trainee', 'Junior', 'Middle', 'Senior');

CREATE TABLE worker (
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    BIRTHDAY DATE CHECK (BIRTHDAY > '1900-01-01'),
    LEVEL VARCHAR(20) NOT NULL,
    SALARY BIGINT CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE client (
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL
);

CREATE TABLE project (
    ID BIGINT NOT NULL PRIMARY KEY,
    CLIENT_ID INT,
    START_DATE DATE,
    FINISH_DATE DATE,
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID)
);

CREATE TABLE project_worker (
    PROJECT_ID INT,
    WORKER_ID INT,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
);

CREATE SEQUENCE worker_seq START WITH 1;
CREATE SEQUENCE client_seq START WITH 1;
CREATE SEQUENCE project_seq START WITH 1;

ALTER TABLE worker ALTER COLUMN ID SET DEFAULT NEXTVAL('worker_seq');
ALTER TABLE client ALTER COLUMN ID SET DEFAULT NEXTVAL('client_seq');
ALTER TABLE project ALTER COLUMN ID SET DEFAULT NEXTVAL('project_seq');